spring.cloud.config.overrideNone: true
eureka:
  client:
#    healthcheck:
#      enabled: true
    instance:
      lease-expiration-duration-in-seconds: 30
      lease-renewal-interval-in-seconds: 10
    service-url:
      defaultZone: http://localhost:3000/eureka/
#==== connect to mysql ======#
datasource:
  auto-test:
    url: jdbc:mysql://118.187.7.77:3307/micro_auto_test?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: jpress
#Swagger Configure Properties
sop.swagger.enable: true
sop.swagger.packageScan: com.springcloud.microautotest
sop.swagger.title: 自动测试，工程api-docs管理
sop.swagger.description: 自动测试，工程api-docs管理
sop.swagger.project: micro-auto-test
sop.swagger.project-parent: micro-parent
sop.swagger.apiVersion: 1.0
server:
  port: 8978
