server:
    port: 3000
spring:
    application:
        name: discover-server
eureka:
    client:
        register-with-eureka: false
        fetch-registry: false
        service-url:
            defaultZone: http://localhost:3000/eureka/
