server:
    port: 8080
spring:
    cloud:
        gateway:
            routes:
                - id: neo_route
                  uri: http://www.ityouknow.com
                  predicates:
                      - Path=/spring-cloud