spring:
  application:
    name: config
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
#        git:
#          uri: https://gitee.com/Zero-One/config-repo  # 远程git仓库的地址
#          username: username  # 以及相应的账户名
#          password: password  # 和密码
#          basedir: E:\Java_IDEA\config\basedir  # 可以使用这个配置项来指定本地git仓库的路径
eureka:
  client:
#    healthcheck:
#      enabled: true
    instance:
      lease-expiration-duration-in-seconds: 30
      lease-renewal-interval-in-seconds: 10
    service-url:
      defaultZone: http://localhost:8080/eureka/
server:
  port: 8974